# Generated by Django 6.1.1 on 2026-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=200)),
                ('author', models.CharField(help_text='Author of the book', max_length=150)),
                ('isbn', models.CharField(help_text='Unique ISBN number', max_length=20, unique=True)),
                ('category', models.CharField(help_text='Genre or Category of the book', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Available stock/quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
